# Generated by Django 3.2 on 2021-05-01 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بازدید'),
        ),
        migrations.AlterField(
            model_name='url',
            name='address',
            field=models.URLField(max_length=512, verbose_name='نشانی اینترنتی'),
        ),
    ]
