# Generated by Django 3.2 on 2021-05-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortener', '0002_auto_20210501_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user',
            new_name='author',
        ),
    ]
