# Generated by Django 3.2 on 2021-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortener', '0007_auto_20210606_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='label',
            field=models.CharField(blank=True, max_length=512, verbose_name='عنوان'),
        ),
    ]
