# Generated by Django 3.2 on 2021-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortener', '0009_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='label',
            field=models.CharField(blank=True, max_length=30, verbose_name='عنوان'),
        ),
    ]
